"""Dados públicos de concorrentes (maio/2026) e hipóteses de automação."""

from __future__ import annotations

from typing import Any

COMPETITORS: list[dict[str, Any]] = [
    {"handle": "@direitonews", "seguidores": 958_000, "camada": "topo", "nicho": "portal jurídico"},
    {"handle": "@visaoefocopolicial", "seguidores": 775_000, "camada": "topo", "nicho": "concursos policiais"},
    {"handle": "@aurylopesjr", "seguidores": 523_000, "camada": "topo", "nicho": "processo penal"},
    {"handle": "@profa.ceresrabelo", "seguidores": 117_000, "camada": "meio", "nicho": "concursos"},
    {"handle": "@profalexandresalim", "seguidores": 99_000, "camada": "meio", "nicho": "direito penal"},
    {"handle": "@concursospoliciais", "seguidores": 95_000, "camada": "meio", "nicho": "concursos policiais"},
    {"handle": "@profissaopolicialoficial", "seguidores": 63_000, "camada": "meio", "nicho": "questões"},
    {"handle": "@profpriscilasilveira", "seguidores": 57_000, "camada": "meio", "nicho": "criminalista"},
    {"handle": "@cursojuridicooficial", "seguidores": 41_000, "camada": "meio", "nicho": "OAB/concursos"},
    {"handle": "@marcelo_daemon", "seguidores": 27_000, "camada": "par_direto", "nicho": "delegado PF + penal"},
    {"handle": "@qapconsultoria", "seguidores": 27_000, "camada": "par_direto", "nicho": "carreiras policiais"},
    {"handle": "@gdconcursosoficial", "seguidores": 24_000, "camada": "par_direto", "nicho": "concursos policiais"},
    {"handle": "@delegadoluizcarlos", "seguidores": None, "camada": "marca", "nicho": "delegado + caso prático"},
]

# Hipóteses qualificadas como vencedoras para marketing automatizado no nicho.
AUTOMATION_HYPOTHESES: list[dict[str, Any]] = [
    {
        "id": "caso-pratico-semanal",
        "nome": "Carrossel Caso Prático Semanal",
        "categoria": "conteudo",
        "status_default": "ativo",
        "impacto": "alto",
        "descricao": "Toda segunda, IA gera carrossel de flagrante/IPL/tipificação com CTA para NaIntegra.",
        "trigger": "cron: seg 08:00",
        "integracao": ["claude", "supabase_storage", "graph_api"],
    },
    {
        "id": "reels-erro-prova",
        "nome": "Reels — Erro Comum em Prova",
        "categoria": "conteudo",
        "status_default": "ativo",
        "impacto": "alto",
        "descricao": "Quarta-feira: Reels curto (60s) desmistificando pegadinha clássica de penal/processo.",
        "trigger": "cron: qua 18:00",
        "integracao": ["claude", "graph_api"],
    },
    {
        "id": "story-quiz",
        "nome": "Story Quiz Interativo",
        "categoria": "engajamento",
        "status_default": "ativo",
        "impacto": "medio",
        "descricao": "Sexta: enquete + caixa de perguntas sobre tema quente do edital; respostas viram ideias.",
        "trigger": "cron: sex 12:00",
        "integracao": ["graph_api", "n8n"],
    },
    {
        "id": "lead-magnet-dm",
        "nome": "Lead Magnet via DM/Comentário",
        "categoria": "conversao",
        "status_default": "ativo",
        "impacto": "alto",
        "descricao": "Palavra-chave «MATERIAL» nos comentários → resposta automática com link + WhatsApp NaIntegra.",
        "trigger": "webhook: instagram_manage_comments",
        "integracao": ["graph_api", "evolution_api", "n8n"],
    },
    {
        "id": "retargeting-cursos",
        "nome": "Retargeting Meta Ads — Visitantes Lex",
        "categoria": "ads",
        "status_default": "pausado",
        "impacto": "alto",
        "descricao": "Público customizado de visitantes naintegracursos.com.br → campanha conversão curso penal.",
        "trigger": "windsor.ai + pixel",
        "integracao": ["meta_ads", "windsor"],
    },
    {
        "id": "gap-concorrentes",
        "nome": "Gap de Conteúdo vs Concorrentes",
        "categoria": "inteligencia",
        "status_default": "ativo",
        "impacto": "medio",
        "descricao": "Mensal: compara temas dos top 5 concorrentes e sugere 5 pautas exclusivas (caso real).",
        "trigger": "cron: 1º dom 10:00",
        "integracao": ["claude", "dashboard"],
    },
    {
        "id": "horario-otimo",
        "nome": "Agendamento no Horário Ótimo",
        "categoria": "publicacao",
        "status_default": "ativo",
        "impacto": "medio",
        "descricao": "Analisa insights e move posts da fila para slots 18h–21h (RJ) com maior alcance.",
        "trigger": "cron: diário",
        "integracao": ["graph_api", "supabase"],
    },
    {
        "id": "faq-comentarios",
        "nome": "Resposta FAQ em Comentários",
        "categoria": "monitoramento",
        "status_default": "ativo",
        "impacto": "medio",
        "descricao": "Detecta perguntas recorrentes (prazos, edital, material) e responde com template aprovado.",
        "trigger": "webhook: comments",
        "integracao": ["graph_api", "claude"],
    },
    {
        "id": "noticia-juridica-rapida",
        "nome": "Resposta Rápida a Notícia Jurídica",
        "categoria": "conteudo",
        "status_default": "pausado",
        "impacto": "alto",
        "descricao": "Monitor RSS/Google Alerts → story + carrossel «o que cai na prova» em até 4h.",
        "trigger": "rss + n8n",
        "integracao": ["claude", "graph_api", "n8n"],
    },
    {
        "id": "depoimento-aluno",
        "nome": "Republicação Depoimento Aprovado",
        "categoria": "social_proof",
        "status_default": "pausado",
        "impacto": "medio",
        "descricao": "Alunos aprovados enviam print → fila de aprovação → story + feed com tag NaIntegra.",
        "trigger": "manual + fila",
        "integracao": ["supabase", "graph_api"],
    },
    {
        "id": "whatsapp-broadcast-semanal",
        "nome": "Broadcast WhatsApp — Resumo da Semana",
        "categoria": "conversao",
        "status_default": "pausado",
        "impacto": "alto",
        "descricao": "Domingo: resumo dos 3 posts + link material gratuito via WhatsApp Cloud/Evolution.",
        "trigger": "cron: dom 19:00",
        "integracao": ["whatsapp_cloud", "evolution_api"],
    },
    {
        "id": "youtube-shorts-crosspost",
        "nome": "Crosspost YouTube Shorts → Reels",
        "categoria": "distribuicao",
        "status_default": "pausado",
        "impacto": "medio",
        "descricao": "Novo Short no YouTube → download + republicação automática no IG com legenda adaptada.",
        "trigger": "youtube webhook",
        "integracao": ["youtube_api", "graph_api", "n8n"],
    },
]

POSITIONING = {
    "diferencial": "Autoridade real de Delegado PF + casos práticos (flagrante, IPL, tipificação)",
    "referencia_crescimento": "@visaoefocopolicial",
    "benchmark_direto": "@marcelo_daemon",
    "publico": "Concurseiros policiais e OAB — foco Direito Penal/Processo Penal",
    "cta_principal": "NaIntegra Cursos — material e mentoria",
}
